/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {};

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Avatar: typeof import('primevue/avatar')['default']
    Button: typeof import('primevue/button')['default']
    ExportButton: typeof import('./../components/ExportButton.vue')['default']
    FlashMessage: typeof import('./../components/FlashMessage.vue')['default']
    Form: typeof import('@primevue/forms/form')['default']
    FormField: typeof import('@primevue/forms/formfield')['default']
    Header: typeof import('./../components/Header.vue')['default']
    InputText: typeof import('primevue/inputtext')['default']
    LoadingScreen: typeof import('./../components/LoadingScreen.vue')['default']
    Menu: typeof import('primevue/menu')['default']
    Message: typeof import('primevue/message')['default']
    Password: typeof import('primevue/password')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Sidebar: typeof import('./../components/Sidebar.vue')['default']
  }
}
