# Builder stage
FROM node:22-alpine AS builder

WORKDIR /app

ENV NODE_OPTIONS="--max-old-space-size=8192"

RUN apk add --no-cache curl && \
    npm install -g corepack && \
    corepack enable && \
    corepack prepare yarn@4.7.0 --activate && \
    yarn set version 4.7.0

COPY package.json yarn.lock .yarnrc.yml ./
COPY .yarn ./.yarn
COPY ./apps ./apps
COPY ./packages ./packages
COPY ./env ./env

RUN yarn install --frozen-lockfile --network-timeout 60000

RUN yarn workspace @intern/api build

# Runtime stage
FROM node:22-alpine

WORKDIR /app

COPY --from=builder /app/env ./env
COPY --from=builder /app/dst ./dst
COPY --from=builder /app/node_modules ./node_modules
COPY --from=builder /app/package.json ./package.json

EXPOSE 8081

CMD ["node", "dst/apps/api/src/server.js"]