# Builder stage
FROM node:22-alpine AS builder

WORKDIR /app

ENV NODE_OPTIONS="--max-old-space-size=8192"

RUN apk add --no-cache curl && \
    npm install -g corepack && \
    corepack enable && \
    corepack prepare yarn@4.1.1 --activate && \
    yarn set version 4.1.1

COPY package.json yarn.lock .yarnrc.yml ./
COPY .yarn ./.yarn
COPY ./apps ./apps
COPY ./packages ./packages
COPY ./infra/nginx ./infra/nginx

RUN yarn install --frozen-lockfile --network-timeout 60000

RUN yarn workspace @intern/front build

# Final image
FROM nginx:alpine

RUN rm -rf /usr/share/nginx/html/*

COPY --from=builder /app/apps/front/dist /usr/share/nginx/html
COPY ./infra/nginx/nginx.conf /etc/nginx/conf.d/default.conf

CMD ["nginx", "-g", "daemon off;"]