name: CI/CD
run-name: Test & Build & Deploy
on: 
  push:
    branches: ["develop"]
jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Set up Node.js (version >=22)
        uses: actions/setup-node@v4
        with:
          node-version: '>=22'

      - name: Install dependencies
        run: yarn install

  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js (version >=22)
        uses: actions/setup-node@v4
        with:
          node-version: '>=22'

      - name: Install Yarn
        run: corepack enable && corepack prepare yarn@4.7.0 --activate

      - name: Restore Yarn dependencies from cache
        run: yarn install --frozen-lockfile

      - name: Run lint and prettier
        run: yarn lint && yarn prettier

  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js (version >=22)
        uses: actions/setup-node@v4
        with:
          node-version: '>=22'

      - name: Restore Yarn dependencies from cache
        run: yarn install --frozen-lockfile

      - name: Build API
        run: yarn build:api

      - name: Build Front
        run: yarn build:front

  deploy:
    needs: [install, lint, build]
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/develop'
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ec2-user
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd ~/intern-source
            sudo git pull origin develop
            docker-compose down api front
            docker-compose up --build -d
            docker system prune -af
